name: note_taking_app
description: A fully local offline-first note taking application.
publish_to: 'none'
version: 1.9.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # Local Storage
  sqflite: ^2.3.0
  path: ^1.8.3

  # UI & Design

  flutter_staggered_grid_view: ^0.7.0
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  path_provider: ^2.1.1


  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  flutter_markdown: ^0.7.7+1
  shared_preferences: ^2.5.4
  dynamic_color: ^1.8.1
  file_picker: ^10.3.7
  http: ^1.6.0
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  animations: ^2.0.11
  flutter_staggered_animations: ^1.0.0
  flutter_quill: ^11.0.0
  markdown_quill: ^4.3.0
  flutter_quill_extensions: ^11.0.0
  markdown: ^7.2.2
  math_expressions: ^2.5.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#18181b"
  adaptive_icon_foreground: "assets/app_icon.png"

flutter_native_splash:
  color: "#18181b"
  image: "assets/app_icon.png"
  android_12:
    color: "#18181b"
    image: "assets/app_icon.png"
  web: false

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik-Italic-VariableFont_wght.ttf
          style: italic
